throttlerLimit: 10
taintToRemove: pod-pacemaker

debugLogging: false
cni:
  maxWaitTimeInSeconds: 60
  primaryName: 10-aws.conflist
  mergedName: 00-merged-pod-pacemaker.conflist

daemon:
  hostPort: 60312

image:
  repository: ghcr.io/woehrl01/pod-pacemaker
  tag: latest
  pullPolicy: IfNotPresent

nodeSelector: {}

tolerations: 
  - effect: "NoSchedule"
  - effect: "NoExecute"

affinity: {}
