apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: deployed
spec:
  steps:
    - try:
        - assert:
            resource:
              apiVersion: apps/v1
              kind: DaemonSet
              metadata:
                name: pod-pacemaker
                namespace: default
        - wait:
            apiVersion: apps/v1
            kind: Pod
            selector: name=pod-pacemaker
            namespace: default
            timeout: 30s
            for:
              condition:
                name: Ready
                value: "true"
        - apply:
            resource:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: sleep
                namespace: default
              spec:
                replicas: 6
                selector:
                  matchLabels:
                    app: sleep
                template:
                  metadata:
                    labels:
                      app: sleep
                  spec:
                    initContainers:
                      - name: sleep
                        image: ubuntu
                        command: ["sleep", "10"]
                    containers:
                      - name: sleep
                        image: ubuntu
                        command: ["sleep", "3600"]
    - try:
        - wait:
            apiVersion: apps/v1
            kind: Deployment
            name: sleep
            namespace: default
            timeout: 20s
            for:
              condition:
                name: Available
                value: "true"
      catch:
        - wait:
            apiVersion: apps/v1
            kind: Deployment
            name: sleep
            namespace: default
            timeout: 60s
            for:
              condition:
                name: Available
                value: "true"
