apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: deployed
spec:
  steps:
    - try:
        - assert:
            resource:
              apiVersion: apps/v1
              kind: DaemonSet
              metadata:
                name: pod-pacemaker
                namespace: default
        - wait:
            apiVersion: v1
            kind: Pod
            selector: name=pod-pacemaker
            namespace: default
            timeout: 1m
            for:
              condition:
                name: ready
      catch:
        - describe:
            apiVersion: v1
            kind: Pod
            selector: name=pod-pacemaker
            namespace: default
        - command:
            entrypoint: kubectl
            args:
              - logs
              - --prefix
              - -l=name=pod-pacemaker
              - -n
              - default
              - --previous
              - -c
              - init-cni
              - --tail
              - "100"
            check:
              (@ == null): true

        - command:
            entrypoint: kubectl
            args:
              - logs
              - --prefix
              - -l=name=pod-pacemaker
              - -n
              - default
              - -c
              - node-daemon
              - --tail
              - "100"
            check:
              (@ == null): true
    - try:
        - apply:
            resource:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: sleep
                namespace: default
              spec:
                replicas: 6
                selector:
                  matchLabels:
                    app: sleep
                template:
                  metadata:
                    labels:
                      app: sleep
                  spec:
                    initContainers:
                      - name: sleep
                        image: ubuntu
                        command: ["sleep", "10"]
                    containers:
                      - name: sleep
                        image: ubuntu
                        command: ["sleep", "3600"]

    - try:
        - wait:
            apiVersion: apps/v1
            kind: Deployment
            name: sleep
            namespace: default
            timeout: 20s
            for:
              condition:
                name: Available
      catch:
        - describe:
            apiVersion: v1
            kind: Pod
            selector: app=sleep
            namespace: default
        - wait:
            apiVersion: apps/v1
            kind: Deployment
            selector: app=sleep
            namespace: default
            timeout: 60s
            for:
              condition:
                name: Available
