apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pod-pacemaker
  labels:
    app.kubernetes.io/name: pod-pacemaker
    app.kubernetes.io/instance: pod-pacemaker
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  selector:
    matchLabels:
      name: pod-pacemaker
  template:
    metadata:
      labels:
        name: pod-pacemaker
        app.kubernetes.io/name: pod-pacemaker
        app.kubernetes.io/instance: pod-pacemaker
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        {{- with .Values.podLabels }}
        {{ toYaml . | nindent 8 }}
        {{ end }}
      annotations:
        pod-pacemaker/skip: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.daemon.metricsPort }}"
        {{- with .Values.podAnnotations }}
        {{ toYaml . | nindent 8 }}
        {{ end }}
    spec:
      serviceAccountName: pod-pacemaker
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{ end }}
      initContainers:
        - name: init-cni
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "./cni-init"
          args:
            - "--cni-bin-dir=/opt/cni/bin"
            - "--cni-config-dir=/etc/cni/net.d"
            - "--max-wait-time-in-seconds={{ .Values.cni.maxWaitTimeInSeconds }}"
            - "--primary-config-name={{ .Values.cni.primaryName }}"
            - "--merged-config-name={{ .Values.cni.mergedName }}"
            - "--namespace-exclusions={{ join "," .Values.namespaceExclusions }}"
            - "--success-on-connection-timeout={{ .Values.cni.successOnConnectionTimeout }}"
            - "--daemon-socket-path={{ .Values.daemon.socketPath }}"
          volumeMounts:
            - name: cni-bin-dir
              mountPath: /opt/cni/bin
            - name: cni-config-dir
              mountPath: /etc/cni/net.d
            - name: pod-pacemaker-socket
              mountPath: {{ .Values.daemon.socketPath }}
      containers:
        - name: node-daemon
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "./node-daemon"
          args:
            - "--taint-to-remove={{ .Values.taintToRemove }}"
            - "--daemon-socket-path={{ .Values.daemon.socketPath }}"
            - "--debug-logging={{ .Values.debugLogging }}"
            - "--metrics-port={{ .Values.daemon.metricsPort }}"
            - "--metrics-enabled={{ .Values.daemon.metricsEnabled }}"
            - "--skip-daemonsets={{ .Values.daemon.skipDaemonsets }}"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: {{ .Values.daemon.metricsPort }}
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{ end }}
      tolerations:
        - key: {{ .Values.taintToRemove }}
          effect: NoSchedule
        {{- with .Values.tolerations }}
        {{ toYaml . | nindent 8 }}
        {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      volumes:
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
            type: DirectoryOrCreate
        - name: cni-config-dir
          hostPath:
            path: /etc/cni/net.d
            type: DirectoryOrCreate
        - name: pod-pacemaker-socket
          hostPath:
            path: {{ .Values.daemon.socketPath }}
            type: FileOrCreate
