apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pod-pacemaker
spec:
  selector:
    matchLabels:
      name: pod-pacemaker
  template:
    metadata:
      labels:
        name: pod-pacemaker
      annotations:
        pod-pacemaker/skip: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.daemon.metricsPort }}"
    spec:
      serviceAccountName: pod-pacemaker
      hostNetwork: true
      initContainers:
        - name: init-cni
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "./cni-init"
          args:
            - "--cni-bin-dir=/opt/cni/bin"
            - "--cni-config-dir=/etc/cni/net.d"
            - "--daemon-port={{ .Values.daemon.hostPort }}"
            - "--max-wait-time-in-seconds={{ .Values.cni.maxWaitTimeInSeconds }}"
            - "--primary-config-name={{ .Values.cni.primaryName }}"
            - "--merged-config-name={{ .Values.cni.mergedName }}"
            - "--namespace-exclusions={{ join "," .Values.namespaceExclusions }}"
          volumeMounts:
            - name: cni-bin-dir
              mountPath: /opt/cni/bin
            - name: cni-config-dir
              mountPath: /etc/cni/net.d
      containers:
        - name: node-daemon
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "./node-daemon"
          args:
            - "--throttler-limit={{ .Values.throttlerLimit }}"
            - "--taint-to-remove={{ .Values.taintToRemove }}"
            - "--daemon-port={{ .Values.daemon.hostPort }}"
            - "--debug-logging={{ .Values.debugLogging }}"
            - "--metrics-port={{ .Values.daemon.metricsPort }}"
            - "--metrics-enabled={{ .Values.daemon.metricsEnabled }}"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: {{ .Values.daemon.hostPort }}
              protocol: TCP
          livenessProbe:
            grpc:
              port: {{ .Values.daemon.hostPort }}
            initialDelaySeconds: 10
      tolerations:
        - key: {{ .Values.taintToRemove }}
          effect: NoSchedule
        {{- with .Values.tolerations }}
        {{ toYaml . | nindent 8 }}
        {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      volumes:
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
            type: DirectoryOrCreate
        - name: cni-config-dir
          hostPath:
            path: /etc/cni/net.d
            type: DirectoryOrCreate
