taintToRemove: pod-pacemaker

debugLogging: false
cni:
  maxWaitTimeInSeconds: 120 # maximum is 220 seconds because of the default CNI timeout of 4 minutes
  successOnConnectionTimeout: true
  mergedName: 00-merged-pod-pacemaker.conflist

daemon:
  socketPath: /var/run/pod-pacemaker/pod-pacemaker.sock
  metricsEnabled: true
  skipDaemonsets: true
  metricsPort: 9000

podAnnotations: {}
podLabels: {}
priorityClassName: "system-node-critical"

image:
  repository: ghcr.io/woehrl01/pod-pacemaker
  pullPolicy: IfNotPresent

nodeSelector: {}

resources: {}

tolerations: 
  - effect: "NoSchedule"
  - effect: "NoExecute"

affinity: {}

namespaceExclusions: 
  - kube-system

defaultThrottleConfig:
  enabled: true
  config:
    maxConcurrent:
      perCore: "0.5"
